# Import Libraries and Dataset

# Wrangling

## Checking Columns Headers

# Standardizing Column Names and Dropping Columns

## 2015

### Renaming Columns

### Dropping Columns

### Checking Data Types

## 2016

### Renaming Columns

### Dropping Columns

### Checking Data Types

## 2017

### Renaming Columns

### Dropping Columns

### Checking Data Types

## 2018

### Renaming Columns

### Dropping Columns

### Checking Data Types

## 2019

### Renaming Columns

### Dropping Columns

### Checking Data Types

## 2020

### Renaming Columns

### Dropping Columns

### Checking Data Types

## 2021

### Renaming Columns

### Dropping Columns

### Checking Data Types

# Concating Tables

## Deriving missing columns

----

# Import Libraries and Dataset

In [5]:
#Import Libraries
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

In [7]:
#Creating Pathway for data
path =(r'C:\Users\colmu\Desktop\Documents\GitHub Documents\CF_Balancing Acts')

In [8]:
#Importing dataset 2015
DF_2015=pd.read_csv(os.path.join(path,'data','Original Data','World Wide Happiness Report','2015.CSV'))
DF_2015.shape

(158, 12)

In [9]:
#Importing dataset 2016
DF_2016=pd.read_csv(os.path.join(path,'data','Original Data','World Wide Happiness Report','2016.CSV'))
DF_2016.shape

(157, 13)

In [10]:
#Importing dataset 2017
DF_2017=pd.read_csv(os.path.join(path,'data','Original Data','World Wide Happiness Report','2017.CSV'))
DF_2017.shape

(155, 12)

In [197]:
#Importing dataset 2018
DF_2018=pd.read_csv(os.path.join(path,'data','Original Data','World Wide Happiness Report','2018.CSV'))
DF_2018.shape

(156, 9)

In [202]:
#Importing dataset 2019
DF_2019=pd.read_csv(os.path.join(path,'data','Original Data','World Wide Happiness Report','2019.CSV'))
DF_2019.shape

(156, 9)

In [87]:
#Importing dataset 2020
DF_2020=pd.read_csv(os.path.join(path,'data','Original Data','World Wide Happiness Report','2020.CSV'))
DF_2020.shape

(153, 20)

In [14]:
#Importing dataset 2021
DF_2021=pd.read_csv(os.path.join(path,'data','Original Data','World Wide Happiness Report','2021.CSV'))
DF_2021.shape

(149, 20)

----------

# Wrangling

## Checking Columns Headers

In [15]:
#checking columns 2015
DF_2015.head(3)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204

In [16]:
#checking columns 2016
DF_2016.head(3)

,Country,Region,Happiness Rank,Happiness Score,Lower Confidence Interval,Upper Confidence Interval,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137

In [17]:
#checking columns 2017
DF_2017.head(3)

,Country,Happiness.Rank,Happiness.Score,Whisker.high,Whisker.low,Economy..GDP.per.Capita.,Family,Health..Life.Expectancy.,Freedom,Generosity,Trust..Government.Corruption.,Dystopia.Residual
0,Norway,1,7.537,7.594445,7.479556,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964,2.277027
1,Denmark,2,7.522,7.581728,7.462272,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770,2.313707
2,Iceland,3,7.504,7.622030,7.385970,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527,2.322715

In [18]:
#checking columns 2018
DF_2018.head(3)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408

In [19]:
#checking columns 2019
DF_2019.head(3)

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341

In [20]:
#checking columns 2020
DF_2020.head(3)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267

In [21]:
#checking columns 2021
DF_2021.head(3)

,Country name,Regional indicator,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.0,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.7,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.4,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839

In [15]:
#checking columns 2015
DF_2015.head(3)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204

-----

Defining Coumn names for all tables:
county, region, standard_error, happiness_rank, happiness_score, social_support, logged_GDP_per_capita, healthy_life_expectancy, freedom_to_make_life_choices, generosity, perceptions_of_corruption.

Columns regarding dystopia, dystopia residual, and dystopia "Explained by" will be dropped

----------

# Standardizing Column Names and Dropping Columns

## 2015

### Renaming Columns

In [189]:
# Renaming 2015 columns
DF_2015.rename(
    columns={"County":"country", "Region":"region", "Happiness Rank":"happiness_rank", "Happiness Score":"happiness_score", "Family":"social_support", "Economy (GDP per Capita)":"logged_GDP_per_capita", "Health (Life Expectancy)":"healthy_life_expectancy", "Freedom":"freedom_to_make_life_choices", "Generosity":"generosity", "Trust (Government Corruption)":"perceptions_of_corruption"},
    inplace=True,
)

DF_2015

,Country,region,happiness_rank,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life choices,perceptions_of_corruption,generosity
0,Switzerland,Western Europe,1,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678
1,Iceland,Western Europe,2,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630
2,Denmark,Western Europe,3,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139
3,Norway,Western Europe,4,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699
4,Canada,North America,5,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811
...,...,...,...,...,...,...,...,...,...,...
153,Rwanda,Sub-Saharan Africa,154,3.465,0.22208,0.77370,0.42864,0.59201,0.55191,0.22628
154,Benin,Sub-Saharan Africa,155,3.340,0.28665,0.35386,0.31910,0.48450,0.08010,0.18260
155,Syria,Middle East and Northern Africa,156,3.006,0.66320,0.47489,0.72193,0.15684,0.18906,0.47179
156,Burundi,Sub-Saharan Africa,157,2.905,0.01530,0.41587,0.22396,0.11850,0.10062,0.19727
157,Togo,Sub-Saharan Africa,158,2.839,0.20868,0.13995,0.28443,0.36453,0.10731,0.16681

### Dropping Columns

In [ ]:
 DF_2015=DF_2015.drop(columns=['Dystopia Residual','standard_error'])

DF_2015.head(3)

### Checking Data Types

In [101]:
#Checking data types
DF_2015.dtypes

Country                          object
region                           object
happiness_rank                    int64
happiness_score                 float64
logged_GDP_per_capita           float64
social_support                  float64
healthy_life_expectancy         float64
freedom_to_make_life choices    float64
perceptions_of_corruption       float64
generosity                      float64
dtype: object

In [32]:
# Checking for mixed type data
for col in DF_2015.columns.tolist():
  weird = (DF_2015[[col]].map(type) != DF_2015[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (DF_2015[weird]) > 0:
    print (col)

----------

## 2016

### Renaming Columns

In [38]:
# Renaming 2016 columns
DF_2016.rename(
    columns={"County":"country", "Region":"region", "Happiness Rank":"happiness_rank", "Happiness Score":"happiness_score", "Family":"social_support", "Economy (GDP per Capita)":"logged_GDP_per_capita", "Health (Life Expectancy)":"healthy_life_expectancy", "Freedom":"freedom_to_make_life_choices", "Generosity":"generosity", "Trust (Government Corruption)":"perceptions_of_corruption"},
    inplace=True,
)

DF_2016

,Country,region,happiness_rank,happiness_score,Lower Confidence Interval,Upper Confidence Interval,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,perceptions_of_corruption,generosity,Dystopia Residual
0,Denmark,Western Europe,1,7.526,7.460,7.592,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171,2.73939
1,Switzerland,Western Europe,2,7.509,7.428,7.590,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083,2.69463
2,Iceland,Western Europe,3,7.501,7.333,7.669,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678,2.83137
3,Norway,Western Europe,4,7.498,7.421,7.575,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895,2.66465
4,Finland,Western Europe,5,7.413,7.351,7.475,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492,2.82596
...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,3.404,3.564,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812
153,Afghanistan,Southern Asia,154,3.360,3.288,3.432,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558
154,Togo,Sub-Saharan Africa,155,3.303,3.192,3.414,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540
155,Syria,Middle East and Northern Africa,156,3.069,2.936,3.202,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789
156,Burundi,Sub-Saharan Africa,157,2.905,2.732,3.078,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404

### Dropping Columns

In [39]:
DF_2016=DF_2016.drop(columns=['Dystopia Residual', 'Lower Confidence Interval', 'Upper Confidence Interval'])

DF_2016.head(3)

,Country,region,happiness_rank,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,perceptions_of_corruption,generosity
0,Denmark,Western Europe,1,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171
1,Switzerland,Western Europe,2,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083
2,Iceland,Western Europe,3,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678

### Checking Data Types

In [40]:
#Checking data types
DF_2016.dtypes

Country                          object
region                           object
happiness_rank                    int64
happiness_score                 float64
logged_GDP_per_capita           float64
social_support                  float64
healthy_life_expectancy         float64
freedom_to_make_life_choices    float64
perceptions_of_corruption       float64
generosity                      float64
dtype: object

In [42]:
# Checking for mixed type data
for col in DF_2016.columns.tolist():
  weird = (DF_2016[[col]].map(type) != DF_2016[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (DF_2016[weird]) > 0:
    print (col)

----------

## 2017

### Renaming Columns

In [176]:
# Renaming 2017 columns
DF_2017.rename(
    columns={"County":"country", "Happiness.Rank":"happiness_rank", "Happiness.Score":"happiness_score", "Family":"social_support", "Economy..GDP.per.Capita.":"logged_GDP_per_capita", "Health..Life.Expectancy.":"healthy_life_expectancy", "Freedom":"freedom_to_make_life_choices", "Generosity":"generosity", "Trust..Government.Corruption.":"perceptions_of_corruption"},
    inplace=True,
)

DF_2017

,Country,happiness_rank,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527
3,Switzerland,4,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007
4,Finland,5,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612
...,...,...,...,...,...,...,...,...,...
150,Rwanda,151,3.471,0.368746,0.945707,0.326425,0.581844,0.252756,0.455220
151,Syria,152,3.462,0.777153,0.396103,0.500533,0.081539,0.493664,0.151347
152,Tanzania,153,3.349,0.511136,1.041990,0.364509,0.390018,0.354256,0.066035
153,Burundi,154,2.905,0.091623,0.629794,0.151611,0.059901,0.204435,0.084148
154,Central African Republic,155,2.693,0.000000,0.000000,0.018773,0.270842,0.280876,0.056565

### Dropping Columns

In [47]:
DF_2017=DF_2017.drop(columns=['Dystopia.Residual', 'Whisker.high", "Whisker.low"])

DF_2017.head(3)

,Country,happiness_rank,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Norway,1,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964
1,Denmark,2,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770
2,Iceland,3,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527

### Checking Data Types

In [48]:
#Checking data types
DF_2017.dtypes

Country                          object
happiness_rank                    int64
happiness_score                 float64
logged_GDP_per_capita           float64
social_support                  float64
healthy_life_expectancy         float64
freedom_to_make_life_choices    float64
generosity                      float64
perceptions_of_corruption       float64
dtype: object

In [49]:
# Checking for mixed type data
for col in DF_2017.columns.tolist():
  weird = (DF_2017[[col]].map(type) != DF_2017[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (DF_2017[weird]) > 0:
    print (col)

----------

## 2018

### Renaming Columns

In [198]:
# Renaming 2018 columns
DF_2018.rename(
    columns={"Country or region":"country", "Overall rank":"happiness_rank", "Score":"happiness_score", "Social support":"social_support", "GDP per capita":"logged_GDP_per_capita", "Healthy life expectancy":"healthy_life_expectancy", "Freedom to make life choices":"freedom_to_make_life_choices", "Generosity":"generosity", "Perceptions of corruption":"perceptions_of_corruption"},
    inplace=True,
)

DF_2018

,happiness_rank,country,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,1,Finland,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,2,Norway,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,3,Denmark,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,4,Iceland,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,5,Switzerland,7.487,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...
151,152,Yemen,3.355,0.442,1.073,0.343,0.244,0.083,0.064
152,153,Tanzania,3.303,0.455,0.991,0.381,0.481,0.270,0.097
153,154,South Sudan,3.254,0.337,0.608,0.177,0.112,0.224,0.106
154,155,Central African Republic,3.083,0.024,0.000,0.010,0.305,0.218,0.038
155,156,Burundi,2.905,0.091,0.627,0.145,0.065,0.149,0.076

### Dropping Columns

No columns to drop

### Checking Data Types

In [199]:
#Checking data types
DF_2018.dtypes

happiness_rank                    int64
country                          object
happiness_score                 float64
logged_GDP_per_capita           float64
social_support                  float64
healthy_life_expectancy         float64
freedom_to_make_life_choices    float64
generosity                      float64
perceptions_of_corruption       float64
dtype: object

In [200]:
# Checking for mixed type data
for col in DF_2018.columns.tolist():
  weird = (DF_2018[[col]].map(type) != DF_2018[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (DF_2018[weird]) > 0:
    print (col)

In [201]:
# reorder columns
DF_2018= DF_2018.reindex(columns=["country","happiness_rank", "happiness_score", "logged_GDP_per_capita","social_support", "healthy_life_expectancy", "freedom_to_make_life_choices", "generosity", "perceptions_of_corruption"])

DF_2018

,country,happiness_rank,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,1,7.632,1.305,1.592,0.874,0.681,0.202,0.393
1,Norway,2,7.594,1.456,1.582,0.861,0.686,0.286,0.340
2,Denmark,3,7.555,1.351,1.590,0.868,0.683,0.284,0.408
3,Iceland,4,7.495,1.343,1.644,0.914,0.677,0.353,0.138
4,Switzerland,5,7.487,1.420,1.549,0.927,0.660,0.256,0.357
...,...,...,...,...,...,...,...,...,...
151,Yemen,152,3.355,0.442,1.073,0.343,0.244,0.083,0.064
152,Tanzania,153,3.303,0.455,0.991,0.381,0.481,0.270,0.097
153,South Sudan,154,3.254,0.337,0.608,0.177,0.112,0.224,0.106
154,Central African Republic,155,3.083,0.024,0.000,0.010,0.305,0.218,0.038
155,Burundi,156,2.905,0.091,0.627,0.145,0.065,0.149,0.076

---

## 2019

### Renaming Columns

In [203]:
# Renaming 2019 columns
DF_2019.rename(
    columns={"Country or region":"country", "Overall rank":"happiness_rank", "Score":"happiness_score", "Social support":"social_support", "GDP per capita":"logged_GDP_per_capita", "Healthy life expectancy":"healthy_life_expectancy", "Freedom to make life choices":"freedom_to_make_life_choices", "Generosity":"generosity", "Perceptions of corruption":"perceptions_of_corruption"},
    inplace=True,
)

DF_2019

,happiness_rank,country,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...
151,152,Rwanda,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,153,Tanzania,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,154,Afghanistan,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,155,Central African Republic,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,156,South Sudan,2.853,0.306,0.575,0.295,0.010,0.202,0.091

### Dropping Columns

No columns to drop

### Checking Data Types

In [204]:
#Checking data types
DF_2019.dtypes

happiness_rank                    int64
country                          object
happiness_score                 float64
logged_GDP_per_capita           float64
social_support                  float64
healthy_life_expectancy         float64
freedom_to_make_life_choices    float64
generosity                      float64
perceptions_of_corruption       float64
dtype: object

In [205]:
# Checking for mixed type data
for col in DF_2019.columns.tolist():
  weird = (DF_2019[[col]].map(type) != DF_2019[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (DF_2019[weird]) > 0:
    print (col)

In [206]:
# reorder columns
DF_2019= DF_2019.reindex(columns=["country","happiness_rank", "happiness_score", "logged_GDP_per_capita","social_support", "healthy_life_expectancy", "freedom_to_make_life_choices", "generosity", "perceptions_of_corruption"])

DF_2019

,country,happiness_rank,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,1,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,Denmark,2,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,Norway,3,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,Iceland,4,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,Netherlands,5,7.488,1.396,1.522,0.999,0.557,0.322,0.298
...,...,...,...,...,...,...,...,...,...
151,Rwanda,152,3.334,0.359,0.711,0.614,0.555,0.217,0.411
152,Tanzania,153,3.231,0.476,0.885,0.499,0.417,0.276,0.147
153,Afghanistan,154,3.203,0.350,0.517,0.361,0.000,0.158,0.025
154,Central African Republic,155,3.083,0.026,0.000,0.105,0.225,0.235,0.035
155,South Sudan,156,2.853,0.306,0.575,0.295,0.010,0.202,0.091

------

## 2020

### Renaming Columns

In [88]:
# Renaming 2020 columns
DF_2020.rename(
    columns={"Country name":"country", "Regional indicator":"region", "Ladder score":"happiness_score", "Social support":"social_support", "Logged GDP per capita":"logged_GDP_per_capita", "Healthy life expectancy":"healthy_life_expectancy", "Freedom to make life choices":"freedom_to_make_life_choices", "Generosity":"generosity", "Perceptions of corruption":"perceptions_of_corruption"},
    inplace=True,
)

DF_2020

,country,region,happiness_score,Standard error of ladder score,upperwhisker,lowerwhisker,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.8087,0.031156,7.869766,7.747634,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445,1.972317,1.285190,1.499526,0.961271,0.662317,0.159670,0.477857,2.762835
1,Denmark,Western Europe,7.6456,0.033492,7.711245,7.579955,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489,1.972317,1.326949,1.503449,0.979333,0.665040,0.242793,0.495260,2.432741
2,Switzerland,Western Europe,7.5599,0.035014,7.628528,7.491272,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728,1.972317,1.390774,1.472403,1.040533,0.628954,0.269056,0.407946,2.350267
3,Iceland,Western Europe,7.5045,0.059616,7.621347,7.387653,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710,1.972317,1.326502,1.547567,1.000843,0.661981,0.362330,0.144541,2.460688
4,Norway,Western Europe,7.4880,0.034837,7.556281,7.419719,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218,1.972317,1.424207,1.495173,1.008072,0.670201,0.287985,0.434101,2.168266
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,0.115183,3.701658,3.250141,6.625160,0.319460,45.200001,0.640881,0.082410,0.891807,1.972317,0.041072,0.000000,0.000000,0.292814,0.253513,0.028265,2.860198
149,Rwanda,Sub-Saharan Africa,3.3123,0.052425,3.415053,3.209547,7.600104,0.540835,61.098846,0.900589,0.055484,0.183541,1.972317,0.343243,0.522876,0.572383,0.604088,0.235705,0.485542,0.548445
150,Zimbabwe,Sub-Saharan Africa,3.2992,0.058674,3.414202,3.184198,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237,1.972317,0.425564,1.047835,0.375038,0.377405,0.151349,0.080929,0.841031
151,South Sudan,Sub-Saharan Africa,2.8166,0.107610,3.027516,2.605684,7.425360,0.553707,51.000000,0.451314,0.016519,0.763417,1.972317,0.289083,0.553279,0.208809,0.065609,0.209935,0.111157,1.378751
152,Afghanistan,South Asia,2.5669,0.031311,2.628270,2.505530,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687,1.972317,0.300706,0.356434,0.266052,0.000000,0.135235,0.001226,1.507236

### Dropping Columns

In [90]:
DF_2020=DF_2020.drop(columns=["Standard error of ladder score", "upperwhisker", "lowerwhisker", "Ladder score in Dystopia", "Explained by: Log GDP per capita", "Explained by: Social support", "Explained by: Healthy life expectancy", "Explained by: Freedom to make life choices", "Explained by: Generosity", "Explained by: Perceptions of corruption", "Dystopia + residual"])

DF_2020.head(3)

,country,region,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,Western Europe,7.8087,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445
1,Denmark,Western Europe,7.6456,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489
2,Switzerland,Western Europe,7.5599,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728

### Checking Data Types

In [91]:
#Checking data types
DF_2020.dtypes

country                          object
region                           object
happiness_score                 float64
logged_GDP_per_capita           float64
social_support                  float64
healthy_life_expectancy         float64
freedom_to_make_life_choices    float64
generosity                      float64
perceptions_of_corruption       float64
dtype: object

In [85]:
# Checking for mixed type data
for col in DF_2020.columns.tolist():
  weird = (DF_2020[[col]].map(type) != DF_2020[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (DF_2020[weird]) > 0:
    print (col)

In [92]:
# reorder columns
DF_2020= DF_2020.reindex(columns=["country","region", "happiness_score", "logged_GDP_per_capita","social_support", "healthy_life_expectancy", "freedom_to_make_life_choices", "generosity", "perceptions_of_corruption"])

DF_2020

,country,region,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,Western Europe,7.8087,10.639267,0.954330,71.900825,0.949172,-0.059482,0.195445
1,Denmark,Western Europe,7.6456,10.774001,0.955991,72.402504,0.951444,0.066202,0.168489
2,Switzerland,Western Europe,7.5599,10.979933,0.942847,74.102448,0.921337,0.105911,0.303728
3,Iceland,Western Europe,7.5045,10.772559,0.974670,73.000000,0.948892,0.246944,0.711710
4,Norway,Western Europe,7.4880,11.087804,0.952487,73.200783,0.955750,0.134533,0.263218
...,...,...,...,...,...,...,...,...,...
148,Central African Republic,Sub-Saharan Africa,3.4759,6.625160,0.319460,45.200001,0.640881,0.082410,0.891807
149,Rwanda,Sub-Saharan Africa,3.3123,7.600104,0.540835,61.098846,0.900589,0.055484,0.183541
150,Zimbabwe,Sub-Saharan Africa,3.2992,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237
151,South Sudan,Sub-Saharan Africa,2.8166,7.425360,0.553707,51.000000,0.451314,0.016519,0.763417
152,Afghanistan,South Asia,2.5669,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687

-------

## 2021

### Renaming Columns

In [94]:
# Renaming 2021 columns
DF_2021.rename(
    columns={"Country name":"country", "Regional indicator":"region", "Ladder score":"happiness_score", "Social support":"social_support", "Logged GDP per capita":"logged_GDP_per_capita", "Healthy life expectancy":"healthy_life_expectancy", "Freedom to make life choices":"freedom_to_make_life_choices", "Generosity":"generosity", "Perceptions of corruption":"perceptions_of_corruption"},
    inplace=True,
)

DF_2021

,country,region,happiness_rank,Standard error of ladder score,upperwhisker,lowerwhisker,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption,Ladder score in Dystopia,Explained by: Log GDP per capita,Explained by: Social support,Explained by: Healthy life expectancy,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual
0,Finland,Western Europe,7.842,0.032,7.904,7.780,10.775,0.954,72.000,0.949,-0.098,0.186,2.43,1.446,1.106,0.741,0.691,0.124,0.481,3.253
1,Denmark,Western Europe,7.620,0.035,7.687,7.552,10.933,0.954,72.700,0.946,0.030,0.179,2.43,1.502,1.108,0.763,0.686,0.208,0.485,2.868
2,Switzerland,Western Europe,7.571,0.036,7.643,7.500,11.117,0.942,74.400,0.919,0.025,0.292,2.43,1.566,1.079,0.816,0.653,0.204,0.413,2.839
3,Iceland,Western Europe,7.554,0.059,7.670,7.438,10.878,0.983,73.000,0.955,0.160,0.673,2.43,1.482,1.172,0.772,0.698,0.293,0.170,2.967
4,Netherlands,Western Europe,7.464,0.027,7.518,7.410,10.932,0.942,72.400,0.913,0.175,0.338,2.43,1.501,1.079,0.753,0.647,0.302,0.384,2.798
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,3.512,0.120,3.748,3.276,7.926,0.787,48.700,0.715,-0.131,0.915,2.43,0.451,0.731,0.007,0.405,0.103,0.015,1.800
145,Botswana,Sub-Saharan Africa,3.467,0.074,3.611,3.322,9.782,0.784,59.269,0.824,-0.246,0.801,2.43,1.099,0.724,0.340,0.539,0.027,0.088,0.648
146,Rwanda,Sub-Saharan Africa,3.415,0.068,3.548,3.282,7.676,0.552,61.400,0.897,0.061,0.167,2.43,0.364,0.202,0.407,0.627,0.227,0.493,1.095
147,Zimbabwe,Sub-Saharan Africa,3.145,0.058,3.259,3.030,7.943,0.750,56.201,0.677,-0.047,0.821,2.43,0.457,0.649,0.243,0.359,0.157,0.075,1.205
148,Afghanistan,South Asia,2.523,0.038,2.596,2.449,7.695,0.463,52.493,0.382,-0.102,0.924,2.43,0.370,0.000,0.126,0.000,0.122,0.010,1.895

### Dropping Columns

In [95]:
DF_2021=DF_2021.drop(columns=["Standard error of ladder score", "upperwhisker", "lowerwhisker", "Ladder score in Dystopia", "Explained by: Log GDP per capita", "Explained by: Social support", "Explained by: Healthy life expectancy", "Explained by: Freedom to make life choices", "Explained by: Generosity", "Explained by: Perceptions of corruption", "Dystopia + residual"])

DF_2021.head(3)

,country,region,happiness_rank,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,Western Europe,7.842,10.775,0.954,72.0,0.949,-0.098,0.186
1,Denmark,Western Europe,7.620,10.933,0.954,72.7,0.946,0.030,0.179
2,Switzerland,Western Europe,7.571,11.117,0.942,74.4,0.919,0.025,0.292

### Checking Data Types

In [96]:
#Checking data types
DF_2021.dtypes

country                          object
region                           object
happiness_rank                  float64
logged_GDP_per_capita           float64
social_support                  float64
healthy_life_expectancy         float64
freedom_to_make_life_choices    float64
generosity                      float64
perceptions_of_corruption       float64
dtype: object

In [97]:
# Checking for mixed type data
for col in DF_2021.columns.tolist():
  weird = (DF_2021[[col]].map(type) != DF_2021[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (DF_2021[weird]) > 0:
    print (col)

In [99]:
# reorder columns
DF_2021= DF_2021.reindex(columns=["country","region", "happiness_score", "logged_GDP_per_capita","social_support", "healthy_life_expectancy", "freedom_to_make_life_choices", "generosity", "perceptions_of_corruption"])

DF_2021

,country,region,happiness_score,logged_GDP_per_capita,social_support,healthy_life_expectancy,freedom_to_make_life_choices,generosity,perceptions_of_corruption
0,Finland,Western Europe,NaN,10.775,0.954,72.000,0.949,-0.098,0.186
1,Denmark,Western Europe,NaN,10.933,0.954,72.700,0.946,0.030,0.179
2,Switzerland,Western Europe,NaN,11.117,0.942,74.400,0.919,0.025,0.292
3,Iceland,Western Europe,NaN,10.878,0.983,73.000,0.955,0.160,0.673
4,Netherlands,Western Europe,NaN,10.932,0.942,72.400,0.913,0.175,0.338
...,...,...,...,...,...,...,...,...,...
144,Lesotho,Sub-Saharan Africa,NaN,7.926,0.787,48.700,0.715,-0.131,0.915
145,Botswana,Sub-Saharan Africa,NaN,9.782,0.784,59.269,0.824,-0.246,0.801
146,Rwanda,Sub-Saharan Africa,NaN,7.676,0.552,61.400,0.897,0.061,0.167
147,Zimbabwe,Sub-Saharan Africa,NaN,7.943,0.750,56.201,0.677,-0.047,0.821
148,Afghanistan,South Asia,NaN,7.695,0.463,52.493,0.382,-0.102,0.924

# Export Data

In [195]:
#Export 2015.csv clean data to “Prepared Data”
DF_2015.to_csv(os.path.join(path,'Data','Prepared Data', '2015_clean.csv'), index=False)

In [196]:
#Export 2016.csv clean data to “Prepared Data”
DF_2016.to_csv(os.path.join(path,'Data','Prepared Data', '2016_clean.csv'), index=False)

In [195]:
#Export 2017.csv clean data to “Prepared Data”
DF_2017.to_csv(os.path.join(path,'Data','Prepared Data', '2017_clean.csv'), index=False)

In [ ]:
#Export 2018.csv clean data to “Prepared Data”
DF_2018.to_csv(os.path.join(path,'Data','Prepared Data', '2018_clean.csv'), index=False)

In [ ]:
#Export 2019.csv clean data to “Prepared Data”
DF_2019.to_csv(os.path.join(path,'Data','Prepared Data', '2019_clean.csv'), index=False)

In [ ]:
#Export 2020.csv clean data to “Prepared Data”
DF_2020.to_csv(os.path.join(path,'Data','Prepared Data', '2020_clean.csv'), index=False)

In [ ]:
#Export 2021.csv clean data to “Prepared Data”
DF_2021.to_csv(os.path.join(path,'Data','Prepared Data', '2021_clean.csv'), index=False)